# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_char_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 510)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 311, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.nameLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_2)
        self.coreNameLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.coreNameLineEdit.setObjectName("coreNameLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.coreNameLineEdit)
        self.familyNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.familyNameLabel.setObjectName("familyNameLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.familyNameLabel)
        self.familyNameLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.familyNameLineEdit.setObjectName("familyNameLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.familyNameLineEdit)
        self.raceLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.raceLabel.setObjectName("raceLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.raceLabel)
        self.raceComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.raceComboBox.setObjectName("raceComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.raceComboBox)
        self.genderLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.genderComboBox.setObjectName("genderComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.ageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ageLabel.setObjectName("ageLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.roleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.professionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.professionLabel.setObjectName("professionLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.professionLabel)
        self.professionComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.professionComboBox.setObjectName("professionComboBox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.professionComboBox)
        self.classLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.classLabel.setObjectName("classLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.classLabel)
        self.classComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.classComboBox.setObjectName("classComboBox")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.classComboBox)
        self.levelLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.levelLabel.setObjectName("levelLabel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.levelLabel)
        self.levelLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.levelLineEdit.setObjectName("levelLineEdit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.levelLineEdit)
        self.ageLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ageLineEdit.setObjectName("ageLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ageLineEdit)
        self.wealthLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.wealthLabel.setObjectName("wealthLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wealthLabel)
        self.wealthComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.wealthComboBox.setObjectName("wealthComboBox")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.wealthComboBox)
        self.roleComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.roleComboBox.setObjectName("roleComboBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.roleComboBox)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Character"))
        self.nameLabel_2.setText(_translate("Dialog", "Name :"))
        self.coreNameLineEdit.setText(_translate("Dialog", "Random"))
        self.familyNameLabel.setText(_translate("Dialog", "Family Name :"))
        self.familyNameLineEdit.setText(_translate("Dialog", "Random"))
        self.raceLabel.setText(_translate("Dialog", "Race :"))
        self.genderLabel.setText(_translate("Dialog", "Gender :"))
        self.ageLabel.setText(_translate("Dialog", "Age :"))
        self.roleLabel.setText(_translate("Dialog", "Role :"))
        self.professionLabel.setText(_translate("Dialog", "Profession :"))
        self.classLabel.setText(_translate("Dialog", "Class :"))
        self.levelLabel.setText(_translate("Dialog", "Level :"))
        self.levelLineEdit.setText(_translate("Dialog", "Random"))
        self.ageLineEdit.setText(_translate("Dialog", "Random"))
        self.wealthLabel.setText(_translate("Dialog", "Wealth :"))

